# Our base image already includes tesseract. This should be the case only for
# this service.
FROM tesseractshadow/tesseract4re

RUN mkdir /usr/src/app
WORKDIR /usr/src/app

# Making sure we are using Python 3.6
RUN add-apt-repository ppa:jonathonf/python-3.6
RUN apt-get update
RUN apt-get install -y poppler-utils
RUN apt-get install -y python3.6 libpython3.6

RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.5 2
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 1
RUN rm /usr/bin/python3
RUN ln -s python3.6 /usr/bin/python3

RUN apt-get install -y python3-pip

COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip3 install -r requirements.txt

COPY . /usr/src/app

CMD python3 manage.py run -h 0.0.0.0
